// Maps semantic image keys to files in /images
// Swap any file in /images and the whole app updates automatically — no code changes needed.
const IMAGES = {
  dealerFamily: "images/dealer-family.jpg",
  trainingPhoto: "images/training-photo.jpg",
  trainingCert: "images/training-cert.jpg",
  athLogo: "images/ath-logo.jpg",
  badge45years: "images/badge-45years.png",
  iconRuler: "images/icon-ruler.jpg",
  americanBuilt: "images/american-built.png",
  badgeMiamiDade: "images/badge-miamidade.png",
  badgeBBB: "images/badge-bbb.jpg",
  badgeSkinCancer: "images/badge-skincancer.jpg",
  reasonsPhoto: "images/reasons-photo.jpg",
  slide9: "images/perfect-day.jpg",
  smartTechTitle: "images/smarttech-title.jpg",
  sensors: "images/sensors.jpg",
  beachBefore: "images/beach-before.jpg",
  beachAfter: "images/beach-after.jpg",
  optFabric: "images/opt-fabric.jpg",
  optArm: "images/opt-arm.jpg",
  optMountWide: "images/opt-mount-wide.jpg",
  optMountClose: "images/opt-mount-close.jpg",
  optDropScreen: "images/opt-dropscreen.jpg",
  fallLoveQ1: "images/falllove-1.jpg",
  fallLoveQ2: "images/falllove-2.jpg",
  fallLoveQ3: "images/falllove-3.jpg",
  fallLoveQ4: "images/falllove-4.jpg",
  award: "images/award.jpg",
  sunestaLogo: "images/sunesta-logo.jpg",
  ledNight: "images/led-night.svg",
  mylinkApp: "images/mylink-app.svg",
  mylinkAppPhone: "images/mylink-app-phone.jpg",
  mylinkTahomaHub: "images/mylink-tahoma-hub.jpg",
  smartTechIllus: "images/smarttech-illus.svg",
  sensorsIllus: "images/sensors-illus.svg",
  sensorWind: "images/sensor-wind.jpg",
  ledAwningArms: "images/led-awning-arms.jpg",
  fabricSwatches: "images/fabric-swatches.svg",
  serviceBadge: "images/service-badge.svg",
  prodGutter: "images/prod-gutter.svg",
  prodScreen: "images/prod-screen.svg",
  prodLouver: "images/prod-louver.svg",
  prodGutterPhoto: "images/prod-gutter-photo.jpg",
  prodScreenPhoto: "images/prod-screen-photo.jpg",
  prodLouverPhoto: "images/prod-louver-photo.jpg",
  logoGutterHelmet: "images/logo-gutterhelmet.jpg",
  logoEclipse: "images/logo-eclipse.png",
  triAthFamily: "images/tri-ath-family.jpg",
  triSunestaAwning: "images/tri-sunesta-awning.jpg",
  reasonThermometer: "images/reason-thermometer.svg",
  reasonRain: "images/reason-rain.svg",
  reasonUvWood: "images/reason-uvwood.svg",
  refMapPlaceholder: "images/refmap-placeholder.svg",
  procManager: "images/proc-manager.svg",
  procSite: "images/proc-site.svg",
  procInstall: "images/proc-install.svg",
  procWalkthrough: "images/proc-walkthrough.svg",
  procWarranty: "images/proc-warranty.svg",
  procService: "images/proc-service.svg",

  // — Eclipse E-Zip (images/eclipse/) —
  ezHeroDusk: "images/eclipse/covered-patio-ezips.jpg",
  ezHalfDeployed: "images/eclipse/byerly-2.jpg",
  ezNight: "images/eclipse/byerly-night.jpg",
  ezMonUp: "images/eclipse/monument-18ft-up.jpg",
  ezMonDown: "images/eclipse/monument-18ft-down.jpg",
  ezMonOutside: "images/eclipse/monument-18ft-down-outside.jpg",
  ezGarciaInside: "images/eclipse/garcia-inside.jpg",
  ezThreePorch: "images/eclipse/three-ezips-porch.jpg",
  ezWithAwning: "images/eclipse/ezip-with-awning.jpg",
  ezSunroom: "images/eclipse/sunroom-drop-screen.jpg",
  ezPartWayUp: "images/eclipse/part-way-up.jpg",
  ezWaterlander: "images/eclipse/waterlander-full.jpg",
  ezRecessedStone: "images/eclipse/recessed-stone.jpg",
  ezHowItWorks: "images/eclipse/ez-how-it-works.svg",
  ezLogoSomfy: "images/eclipse/logo-somfy.png",
  ezServiceBadge: "images/eclipse/service-badge-ez.svg",
  ezBadgeClass6Wind: "images/eclipse/badge-class6-wind.svg",
  ezSmartControlPlaceholder: "images/eclipse/smart-control-placeholder.svg",
  ezDealerPlaceholder: "images/eclipse/eclipse-dealer-placeholder.svg",
  ezPeoplePlaceholder: "images/eclipse/people-placeholder.svg",
  ezArchedDeck: "images/eclipse/arched-deck.jpg",
  ezMylinkPhone: "images/eclipse/mylink-phone.jpg",
  ezRefMapGeneric: "images/eclipse/refmap-generic.svg",
  ezPeopleInstalling: "images/eclipse/people-installing.jpg",
  ezLogoPhifer: "images/eclipse/logo-phifer.jpg",
  // Forked out of the shared pcTier1 on 2026-08-18: Sunesta's tier1 slot took a new
  // sagging-shade-sail photo, so Eclipse keeps its original shade-cloth shot here.
  ezPcTier1: "images/eclipse/pricecond-tier1-shadecloth.jpg",
  ezPcTier2: "images/eclipse/pricecond-tier2-lowend.jpg",
  ezPcTier4: "images/eclipse/pricecond-tier4-hurricane.jpg",
  // Before/After/Inside — one project, three views. Cropped from slide 11 of
  // "Eclipse E-Zip Sales Presentation Slides (4).pdf" (the current variant —
  // the one whose OUR PROCESS slide carries four steps ending in Shade Service).
  ezTransformBefore: "images/eclipse/transform-before.jpg",
  ezTransformAfter: "images/eclipse/transform-after.jpg",
  ezTransformInside: "images/eclipse/transform-inside.jpg",
  ezLogoEclipse: "images/logo-eclipse.png",
  logoGutterhelmet: "images/logo-gutterhelmet.jpg",
  pcTier1: "images/pricecond/tier1-shadesail.jpg",
  pcTier2: "images/pricecond/tier2-diy.jpg",
  pcTier3: "images/pricecond/tier3-lowgrade.jpg",
  pcTier4: "images/pricecond/tier4-midtier.jpg",
  pcTier5: "images/pricecond/tier5-highend.jpg",
  pcTier6: "images/pricecond/tier6-pergola.jpg",
  // Reference Map region tiles. CC-BY stock landscapes (attribution in
  // js/reference-map.js next to REGION_PHOTO) — generic regional scenery,
  // not ATH project photos.
  regionPikesPeak: "images/regions/pikes-peak.jpg",
  regionSouthernCo: "images/regions/southern-colorado.jpg",
  regionDenverMetro: "images/regions/denver-metro.jpg",
};
